#!/bin/bash

# Permissions: Make sure that chmod +x script has been executed
# Usage: ./script

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "$SCRIPT_DIR/.." || { echo "Failed to move up one directory"; exit 1; }

if [ ! -f .venv/bin/activate ]; then
  echo "Virtual environment not found."
  exit 1
fi

source .venv/bin/activate || { echo "Failed to activate virtual environment"; exit 1; }

python -m tick_architecture.real_time_processor || { echo "Python script failed"; exit 1; }

echo "Script completed successfully."
exit 0