#!/bin/bash

# Permissions: Make sure that chmod +x script has been executed
# Usage: ./script

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "Current directory is: $SCRIPT_DIR"

cd "$SCRIPT_DIR/.." || { echo "Failed to move up one directory"; exit 1; }

source .venv/bin/activate || { echo "Failed to activate virtual environment"; exit 1; }

DATA_DIR="$HOME/CSVs/AAPL/trades"
DATABASE_DIR="$HOME/DB"
TABLE_NAME="trades"
START_DATE="2025.04.01"
END_DATE="2025.04.30"
MARKET_OPEN_TIMESPAN="13:30:00.000000000"
MARKET_CLOSE_TIMESPAN="20:00:00.000000000"

python -m trades_historical_database.returns_table_script "$DATA_DIR" "$DATABASE_DIR" "$TABLE_NAME" "$START_DATE" "$END_DATE" "$MARKET_OPEN_TIMESPAN" "$MARKET_CLOSE_TIMESPAN"

echo "Script executed successfully."