#!/bin/bash

# Permissions: Make sure that chmod +x script has been executed
# Usage: ./script

set -e

cd ..

TRADES_DIR="$HOME/CSVs/IBM/trades/2025.06_IBM_trades.csv"
QUOTES_DIR="$HOME/CSVs/IBM/quotes/2025.06_IBM_quotes.csv"


cd q_scripts

q bid_ask_spread_dataset_creator.q \
  -param1 "$TRADES_DIR" \
  -param2 "$QUOTES_DIR" \
  -param3 2025.06.16D13:30:00.000000000 \
  -param4 2025.06.16D20:00:00.000000000

# sudo lsof -i :5002 List process using that specific port.