#!/bin/bash

# Permissions: Make sure that chmod +x script has been executed
# Usage: ./script

set -e

TRADES_DIR="$HOME/CSVs/IBM/trades/2025.06_IBM_trades.csv"

cd ..

cd q_scripts

echo "Current directory is: $(pwd)"

q candlestick_dataset_creator.q \
  -param1 "$TRADES_DIR" \
  -param2 13:30:00.000000000 \
  -param3 20:00:00.000000000

# sudo lsof -i :5001 List process using that specific port.